// <auto-generated />
namespace DMCombatScreen.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class movedTotalInitiativeFromCharacterToAttendance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(movedTotalInitiativeFromCharacterToAttendance));
        
        string IMigrationMetadata.Id
        {
            get { return "201907031510596_movedTotalInitiativeFromCharacterToAttendance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
